### ISSUE TITLE
Request: Could you please add a notification when a URL is visited?

### ISSUE THREAD

**Issue by fortepc** [SosthenG/yourls-notifier#1]
I found another plugin that triggers on URL click, https://github.com/gehwissenlos/Yourls-Email-Notify but it only sends emails, which doesn't work for a self hosted instance on a residential internet connection that blocks outgoing emails. 

Is there any chance I could convince you to add a notification when a URL is visited?

**Comment by SosthenG** [comment]
Sorry for the delay I totally missed the notification.
If you still need this, could you explain what kind of notification you want because I think the plugin you linked also notifies when a new link is added like mine.
Do you want a notification every time a link is clicked (or accessed)?

Edit : If it's what you want it's done, you can download the [latest release](https://github.com/SosthenG/yourls-notifier/releases/latest).
