### ISSUE TITLE
Add total clicks count to notification

### ISSUE THREAD

**Issue by kanadiou** [SosthenG/yourls-notifier#2]
Hello,
the plungin works perfectly except it send notification when it is clicked but just once.
is it possible to send notification for each clic with the number of total clics ?

thanks

**Comment by SosthenG** [comment]
Hello,

The notification is binded to the Yourls "redirect_shorturl" action, so everytime Yourls counts a click, it should send a notification.
I think your issue is with your browser cache, as Yourls redirection are 301 (Moved permanently), your browser save the target url in cache and will no longer call the short url for further clicks.
If you try to clear your cache and click again (or use a different browser), I think it should work.

For the number of total clicks this is definitly something that can be added, I'll look into it, thanks for the suggestion.

**Comment by kanadiou** [comment]
Yes, you're right, so it wasn't an issue !
It's true that if you click on the link several times from the same browser it doesn't work, but i tried changing browser or computer it does work, which is logical, you're right.
So it might be a feature request to add the total number of clicks in the notification. Not necessarily compulsory but it could be useful.
thank you for your plugin, very usefull !

**Comment by SosthenG** [comment]
Added clicks count in [1.2](https://github.com/SosthenG/yourls-notifier/releases/tag/1.2)
